163 interactive testing documentation
MaileTechnical/CarPark pull request #167
Opened 2023-10-26 23:30 UTC by amullarney

2023-10-26 23:32 UTC, amullarney commented
Deleted anachronistic step-by-step instruction that no longer apply to InteractiveTesting. Updated ReadMe.

2023-10-27 00:25 UTC, johnrwolfe requested changes
The additions look great.  Just a couple embedded comments below.

2023-10-27 00:25 UTC, johnrwolfe commented on InteractiveTesting/models/InteractiveTesting/Components/InteractiveTestbench/TestCases_Nominal/NominalBucket/NominalBucket.xtuml
> +	'A test bucket which runs a state machine to executes a series of test cases.',
Typo: "...to executes a..."

2023-10-27 00:25 UTC, johnrwolfe commented on InteractiveTesting/models/InteractiveTesting/Components/InteractiveTestbench/TestCases_Nominal/UC11_NominalExit/UC11_NominalExit.xtuml
> +	'c',
I've not loaded this branch and looked at it with the editor, but the 'c' on line 8 concerns me.

2023-10-27 19:17 UTC, merged